### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by lidaobing** [Co2333/FishUpgrade#1]
Showing Recent Messages
No account for team "M4Z5DVY94F". Add a new account in the Accounts preference pane or verify that your accounts have valid credentials.

Showing Recent Messages
No signing certificate "Mac Development" found: No "Mac Development" signing certificate matching team ID "M4Z5DVY94F" with a private key was found.

**Comment by Lakr233** [comment]
You need to change it to “Sign to run locally”.
