### ISSUE TITLE
build failed: Package resolution errors must be fixed before building

### ISSUE THREAD

**Issue by lidaobing** [Co2333/FishUpgrade#4]
$ git describe --tags
1.0.2-1-g9833b2c

/Users/lidaobing/workspace/foss/FishUpgrade/FishUpgrade.xcodeproj Missing package product 'AuxiliaryExecute'
x-xcode-log://2B5A00B4-09E2-4EA0-8B7E-E59D98867530 Package resolution errors must be fixed before building

**Comment by Lakr233** [comment]
This is Xcode issue.
